"""Golden-file test: regenerate JSON from the real source .ods and diff
against the checked-in goldens.

Goldens are regenerated by running the CLI against `data/cameo-database.ods`
when the source updates; see the README runbook.

Volatile fields (generated_at) are stripped before comparison so the test is
deterministic.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cameo_convert.filter import clean, full
from cameo_convert.reader import read
from cameo_convert.transform import invert
from cameo_convert.writers.base import dataset_to_dict

REPO = Path(__file__).parent.parent
SOURCE = REPO / "data" / "cameo-database.ods"
GOLDENS = Path(__file__).parent / "goldens"

# When the user runs `pytest --regen-goldens`, the test rewrites the goldens.
REGEN_FLAG = "--regen-goldens"


def _scrub(obj):
    """Strip fields that change every run (timestamps)."""
    if isinstance(obj, dict):
        return {
            k: _scrub(v) for k, v in obj.items() if k != "generated_at"
        }
    if isinstance(obj, list):
        return [_scrub(v) for v in obj]
    return obj


def _generated(variant: str) -> dict:
    entries, meta = read(SOURCE)
    base = invert(
        entries,
        source_file=SOURCE.name,
        source_last_updated=meta.last_updated or meta.up_to_date_with_set,
        release_tag="",
    )
    ds = clean(base) if variant == "clean" else full(base)
    return dataset_to_dict(ds)


def _golden(variant: str) -> dict:
    return json.loads((GOLDENS / f"cards-{variant}.json").read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def regen(request):
    return request.config.getoption(REGEN_FLAG, default=False)


@pytest.mark.skipif(not SOURCE.exists(), reason="source .ods not present")
@pytest.mark.parametrize("variant", ["clean", "full"])
def test_golden(variant, regen):
    generated = _generated(variant)
    if regen:
        (GOLDENS / f"cards-{variant}.json").write_text(
            json.dumps(generated, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        pytest.skip(f"regenerated cards-{variant}.json")

    golden = _golden(variant)
    assert _scrub(generated) == _scrub(golden), (
        f"Generated {variant} output diverges from goldens/cards-{variant}.json. "
        f"If the change is intentional, regenerate with: pytest {REGEN_FLAG}"
    )
