"""ODS writer — round-trip-friendly for LibreOffice users.

Hand-author the XML (same approach as the test fixture builder). odfpy could
work but produces a heavier output for what's essentially a flat table.
"""

import zipfile
from pathlib import Path
from xml.sax.saxutils import escape

from cameo_convert.model import InvertedDataset
from cameo_convert.writers.base import FLAT_COLUMNS, flat_rows, metadata_dict

MIMETYPE = "application/vnd.oasis.opendocument.spreadsheet"

_MANIFEST = """<?xml version="1.0" encoding="UTF-8"?>
<manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.2">
 <manifest:file-entry manifest:full-path="/" manifest:version="1.2" manifest:media-type="application/vnd.oasis.opendocument.spreadsheet"/>
 <manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/>
 <manifest:file-entry manifest:full-path="meta.xml" manifest:media-type="text/xml"/>
</manifest:manifest>"""


def _meta_xml(dataset: InvertedDataset) -> str:
    meta = metadata_dict(dataset)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<office:document-meta xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"\n'
        ' xmlns:dc="http://purl.org/dc/elements/1.1/" office:version="1.2">\n'
        " <office:meta>\n"
        f"  <dc:date>{escape(meta['generated_at'])}</dc:date>\n"
        f"  <dc:description>Generated by cameo-convert {dataset.generator_version} from {escape(dataset.source_file)}</dc:description>\n"
        " </office:meta>\n"
        "</office:document-meta>\n"
    )


def _cell_xml(value: object) -> str:
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return (
            f'<table:table-cell office:value-type="float" office:value="{value}">'
            f"<text:p>{escape(str(value))}</text:p>"
            "</table:table-cell>"
        )
    s = "" if value is None else str(value)
    return (
        '<table:table-cell office:value-type="string">'
        f"<text:p>{escape(s)}</text:p>"
        "</table:table-cell>"
    )


def _row_xml(values: list) -> str:
    return "<table:table-row>" + "".join(_cell_xml(v) for v in values) + "</table:table-row>"


def _content_xml(dataset: InvertedDataset) -> str:
    head = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<office:document-content"
        ' xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"'
        ' xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0"'
        ' xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"'
        ' office:version="1.2">'
        "<office:body><office:spreadsheet>"
    )
    parts = [head]

    parts.append('<table:table table:name="metadata">')
    for k, v in metadata_dict(dataset).items():
        parts.append(_row_xml([k, "" if v is None else v]))
    parts.append("</table:table>")

    parts.append('<table:table table:name="cameos">')
    parts.append(_row_xml(FLAT_COLUMNS))
    for row in flat_rows(dataset):
        parts.append(_row_xml([row[col] for col in FLAT_COLUMNS]))
    parts.append("</table:table>")

    parts.append("</office:spreadsheet></office:body></office:document-content>")
    return "".join(parts)


class OdsWriter:
    name = "ods"
    extension = "ods"

    def write(self, dataset: InvertedDataset, path: Path) -> None:
        with zipfile.ZipFile(path, "w", zipfile.ZIP_STORED) as z:
            z.writestr("mimetype", MIMETYPE)
        with zipfile.ZipFile(path, "a", zipfile.ZIP_DEFLATED) as z:
            z.writestr("META-INF/manifest.xml", _MANIFEST)
            z.writestr("meta.xml", _meta_xml(dataset))
            z.writestr("content.xml", _content_xml(dataset))
